"""Shared data models for adaptive immune intelligence."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Literal

FeedbackVerdict = Literal["true_positive", "false_positive", "benign", "unknown"]
RecommendationAction = Literal["monitor", "raise_priority", "lower_priority", "add_allowlist_candidate", "add_blocklist_candidate"]


@dataclass(frozen=True, slots=True)
class AnalystFeedback:
    """Human feedback used to adapt confidence and policy recommendations."""

    pattern_key: str
    verdict: FeedbackVerdict
    confidence_delta: float = 0.0
    notes: str = ""
    observed_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


@dataclass(frozen=True, slots=True)
class LearnedPattern:
    """Aggregated behavior learned from immune memory and feedback."""

    pattern_key: str
    incident_type: str
    occurrences: int
    average_confidence: float
    average_recurrence: float
    top_features: list[str] = field(default_factory=list)
    last_seen: str | None = None


@dataclass(frozen=True, slots=True)
class PolicyRecommendation:
    """Explainable suggestion generated by adaptive intelligence."""

    action: RecommendationAction
    confidence: float
    reason: str
    pattern_key: str | None = None
    evidence: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class AdaptiveAssessment:
    """Adaptive assessment for a candidate incident or fingerprint."""

    adaptive_score: float
    confidence: float
    recurrence_score: float
    similar_incident_count: int
    top_matches: list[dict[str, Any]] = field(default_factory=list)
    recommendations: list[PolicyRecommendation] = field(default_factory=list)
    reasons: list[str] = field(default_factory=list)
